# image: maven:3.8.5-openjdk-17 
# image: openjdk:17 
image: ubuntu:20.04
# image: maven:3.8.5-eclipse-temurin-17

stages:
  - before_script
  - build
  - test

before_script:
  - apt-get update -y 
  - apt-get install -y openjdk-17-jdk 
  - apt-get install -y maven 
  - apt-get install -y xvfb 
  - apt-get install -y libxext6 
  - apt-get install -y libxrender1 
  - apt-get install -y libxtst6 
  - apt-get install -y libxi6
  - java -version
  - mvn --version
  - Xvfb :99 -screen 0 1024x768x16 &
  - export DISPLAY=:99

build:
    stage: build
    script:
        - cd pixel-editor
        - mvn clean compile

test:
    stage: test
    script:
        - cd pixel-editor
        - timeout 10 mvn clean compile exec:java || true
        - mvn test
        - kill %1